[package]
name = "darvos"
version = "0.1.0"
edition = "2024"

[dependencies]
evdev = "0.13.2"
tokio = { version = "1.47.1", features = ["macros", "time"] }
futures = { version = "0.3", features = ["std"] }
openrgb2 = "0.3.0"
nix = { version = "0.30.1", features = ["user"] }
